# -*- coding: utf-8 -*-
"""Data Exploration and Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DqfcPKjCVOFGmGlCowCPae3yurduGMjs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive

df = pd.read_csv("/content/drive/MyDrive/Dataset .csv")

df

df.fillna(0)

df.dropna(axis=0,inplace=True)

df

sns.pairplot(df,hue="Aggregate rating")

plt.hist(df["Aggregate rating"],bins=25);