# -*- coding: utf-8 -*-
"""Geospatial analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T01kD7pl2xv_BjbaHlnxgWudhSR4r0Q1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive

df = pd.read_csv('/content/drive/MyDrive/Dataset .csv')

df

rating_mapping = {'Excellent': 5, 'Very Good': 4, 'Good': 3, 'Average': 2, 'Poor': 1}

df['Rating Value'] = df['Rating text'].map(rating_mapping)

plt.figure(figsize=(12, 8))
plt.scatter(df['Longitude'], df['Latitude'], c=df['Rating Value'], cmap='viridis', alpha=0.7, edgecolors='k')
plt.colorbar(label='Rating Value')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Restaurant Locations and Ratings')
plt.grid(True)
plt.show()

plt.figure(figsize=(14, 27))
city_counts = df['City'].value_counts().sort_values(ascending=False)
sns.barplot(x=city_counts.values, y=city_counts.index, palette='viridis')
plt.xlabel('Number of Restaurants')
plt.ylabel('City')
plt.title('Distribution of Restaurants Across Cities')
plt.show()

if 'Country' in df.columns:
    plt.figure(figsize=(10, 6))
    country_counts = df['Country'].value_counts().sort_values(ascending=False)
    sns.barplot(x=country_counts.values, y=country_counts.index, palette='viridis')
    plt.xlabel('Number of Restaurants')
    plt.ylabel('Country')
    plt.title('Distribution of Restaurants Across Countries')
    plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Longitude', y='Latitude', hue='Rating Value', data=df, palette='viridis', alpha=0.7)
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Correlation Between Location and Rating')
plt.legend(title='Rating')
plt.grid(True)
plt.show()