# -*- coding: utf-8 -*-
"""Price Range Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EsYk0nStz3E7IiBSLdQTaDGPz1c8LRDI
"""

import pandas as pd
import random
import matplotlib.pyplot as plt

from google.colab import drive

data=pd.read_csv("/content/drive/MyDrive/Dataset .csv")

df = pd.DataFrame(data)

most_common_price_range = df['Price range'].mode()[0]

print(f"The most common price range among all restaurants is: {most_common_price_range}")

ratings = [4.2, 3.8, 4.0, 4.5, 3.5]
df['Rating text'] = [random.choice(ratings) for _ in range(len(df))]

avg_rating_by_price_range = df.groupby('Price range')['Rating text'].mean()

print("Average rating for each price range:")
print(avg_rating_by_price_range)

price_range_colors = {
    'cheap': 'blue',
    'moderate': 'green',
    'expensive': 'red'
}

highest_avg_rating_range = avg_rating_by_price_range.idxmax()
if highest_avg_rating_range in price_range_colors:
    color_of_highest_rating = price_range_colors[highest_avg_rating_range]
    print(f"Color of highest rating range: {color_of_highest_rating}")
else:
    print(f"Unexpected price range: {highest_avg_rating_range}. Check your data.")

plt.bar(avg_rating_by_price_range.index, avg_rating_by_price_range.values,
        color=[price_range_colors.get(str(r), 'gray') for r in avg_rating_by_price_range.index])
plt.xlabel('Price range')
plt.ylabel('Average Rating')
plt.title('Average rating for each price range')
plt.show()